org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=grow_forever
modName=Grow Forever
modLicense=BSD 2-Clause
modGroupId=io.github.makaseloli
modAuthors=makaseloli
modDescription=A mod where bamboo, cactus, and sugar cane grow forever.
modDisplayUrl=https://github.com/makaseloli/Grow-Forever
modIssueTrackerUrl=https://github.com/makaseloli/Grow-Forever/issues
modCredits=


## Fabric Mod Properties
modFabricEnvironment=*
modFabricEntrypoint=io.github.makaseloli.grow_forever.ModMain
modFabricClientEntrypoint=io.github.makaseloli.grow_forever.client.ModClient
